services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3030:5173"
    volumes:
      - ./app:/frontend
    env_file:
      - ./.env
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8088:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - ./.env

  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 8090:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080

volumes:
  frontend:
  pgdata:
