services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3030:5173"
    volumes:
      - ./app:/frontend
    env_file:
      - ./.env
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8088:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - ./.env

volumes:
  frontend:
