# Generated by Django 5.1.2 on 2024-12-05 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body', models.CharField(max_length=20000)),
                ('summary', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sound_url', models.URLField()),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcribe.transcription')),
            ],
        ),
    ]
