name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: pull_request
jobs:
  buildAPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run:
        working-directory: api
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
